# Deployment for container2 (exposed to the internet)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: container2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container2-deployment
  template:
    metadata:
      labels:
        app: container2-deployment
    spec:
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: container-pvc
      containers:
        - name: container2
          image: us-central1-docker.pkg.dev/western-notch-453423-p9/csci5409/container2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - mountPath: /siddik_PV_dir
              name: shared-volume